
import React, { useState, useEffect, useRef } from 'react';
import { X, Mic, MicOff, AlertCircle, ShieldAlert, CheckCircle, Info, FileSearch } from 'lucide-react';
import { GoogleGenAI, LiveServerMessage, Modality } from '@google/genai';
import { LegalReport, RiskLevel, ConversationTurn } from '../types';
import { SCAM_CATEGORIES, THAI_SCAM_LAWS } from '../constants';

interface LiveProtectorProps {
  onComplete: (report: LegalReport) => void;
  onCancel: () => void;
}

export const LiveProtector: React.FC<LiveProtectorProps> = ({ onComplete, onCancel }) => {
  const [isRecording, setIsRecording] = useState(false);
  const [riskScore, setRiskScore] = useState(0);
  const [transcription, setTranscription] = useState<ConversationTurn[]>([]);
  const [detectedSignals, setDetectedSignals] = useState<string[]>([]);
  const [processing, setProcessing] = useState(false);
  
  // Audio state refs
  const audioContextRef = useRef<AudioContext | null>(null);
  const sessionRef = useRef<any>(null);
  const nextStartTimeRef = useRef(0);
  const sourcesRef = useRef(new Set<AudioBufferSourceNode>());

  // Simplified demo simulation for when API is unavailable or for UX flow
  const [demoMode, setDemoMode] = useState(true);

  const startAnalysis = async () => {
    setIsRecording(true);
    setProcessing(true);
    
    // In a real environment, we would initialize the Gemini Live API here.
    // For this prototype, we'll simulate the "Scam Detection" flow.
    
    const demoMessages: Partial<ConversationTurn>[] = [
      { role: 'scammer', text: "Hello, this is the Department of Special Investigation (DSI)." },
      { role: 'scammer', text: "We found your bank account involved in money laundering." },
      { role: 'scammer', text: "You must transfer your funds to our safe account for verification." },
      { role: 'scammer', text: "If you hang up, an arrest warrant will be issued immediately." }
    ];

    let count = 0;
    const interval = setInterval(() => {
      if (count >= demoMessages.length) {
        clearInterval(interval);
        setProcessing(false);
        return;
      }
      
      const turn = demoMessages[count] as ConversationTurn;
      setTranscription(prev => [...prev, { ...turn, timestamp: Date.now() }]);
      
      // Update Risk Logic
      if (count === 1) {
        setRiskScore(45);
        setDetectedSignals(prev => [...prev, "Authority Impersonation"]);
      } else if (count === 2) {
        setRiskScore(75);
        setDetectedSignals(prev => [...prev, "Financial Request", "Urgency"]);
      } else if (count === 3) {
        setRiskScore(95);
        setDetectedSignals(prev => [...prev, "Threat/Coercion"]);
      }
      
      count++;
    }, 4000);

    return () => clearInterval(interval);
  };

  const handleFinish = async () => {
    setProcessing(true);
    // Simulate generation of the legal report via Gemini 3 Flash
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // In reality, we'd send the full transcript to Gemini to format.
    // Here we generate a structured response locally for the demo.
    setTimeout(() => {
      const report: LegalReport = {
        id: Math.random().toString(36).substr(2, 9),
        date: new Date().toISOString(),
        summary: "Possible 'DSI' Call Center Scam detected. Fraudster attempted to coerce the user into transferring funds under the guise of a criminal investigation.",
        transcription: transcription,
        riskAssessment: {
          level: riskScore > 80 ? RiskLevel.CRITICAL : RiskLevel.HIGH,
          reasons: detectedSignals
        },
        thaiLawSections: [
          {
            section: "Section 341",
            description: "Fraud",
            relevance: "The offender used deception regarding their identity (DSI officer) to attempt to gain assets."
          },
          {
            section: "Section 342(1)",
            description: "Fraud by Impersonation",
            relevance: "Specifically impersonating a government official."
          }
        ],
        policeReadyDraft: `TO: Royal Thai Police Station\n\nSUBJECT: Formal Complaint of Attempted Fraud (Call Center Scam)\n\nI, [YOUR NAME], wish to report a scam attempt that occurred on ${new Date().toLocaleString()}. The caller identified themselves as a 'DSI Officer' and stated my accounts were being investigated for money laundering. They demanded a transfer of funds to a 'Safe Account'. This constitutes attempted fraud under Thai Criminal Code Section 341 and 342. Attached is the digital transcript and risk analysis generated by AntiScam AI.`
      };
      onComplete(report);
    }, 2000);
  };

  return (
    <div className="flex flex-col h-full bg-gray-900 text-white animate-in slide-in-from-bottom duration-500">
      {/* Header */}
      <div className="p-6 flex items-center justify-between border-b border-white/10">
        <div className="flex items-center gap-3">
          <div className="w-3 h-3 bg-red-500 rounded-full animate-pulse"></div>
          <span className="text-sm font-bold tracking-widest uppercase">Live Analysis</span>
        </div>
        <button onClick={onCancel} className="p-2 bg-white/10 rounded-full">
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Main Analysis Display */}
      <div className="flex-1 overflow-y-auto p-6 space-y-8 scroll-smooth">
        {/* Large Risk Meter */}
        <div className="flex flex-col items-center justify-center py-10">
          <div className="relative w-48 h-48 flex items-center justify-center">
             <svg className="w-full h-full -rotate-90">
               <circle cx="96" cy="96" r="88" stroke="currentColor" strokeWidth="12" fill="transparent" className="text-white/10" />
               <circle cx="96" cy="96" r="88" stroke="currentColor" strokeWidth="12" fill="transparent" 
                       strokeDasharray={552} 
                       strokeDashoffset={552 - (552 * riskScore) / 100}
                       className={`transition-all duration-1000 ease-out ${riskScore > 80 ? 'text-red-500' : riskScore > 50 ? 'text-orange-500' : 'text-green-500'}`} />
             </svg>
             <div className="absolute inset-0 flex flex-col items-center justify-center">
               <span className="text-5xl font-black">{riskScore}%</span>
               <span className="text-xs font-bold uppercase tracking-widest opacity-60">Risk Level</span>
             </div>
          </div>
          {riskScore > 70 && (
            <div className="mt-6 flex items-center gap-2 px-4 py-2 bg-red-500 text-white rounded-full text-sm font-bold animate-bounce">
              <ShieldAlert className="w-4 h-4" /> SCAM DETECTED
            </div>
          )}
        </div>

        {/* Detected Signals */}
        <div className="space-y-4">
          <h3 className="text-xs font-black uppercase text-white/40 tracking-widest flex items-center gap-2">
            <FileSearch className="w-4 h-4" /> Detected Signals
          </h3>
          <div className="flex flex-wrap gap-2">
            {detectedSignals.length === 0 ? (
              <p className="text-sm text-white/30 italic">Monitoring conversation context...</p>
            ) : (
              detectedSignals.map((sig, i) => (
                <span key={i} className="px-3 py-1.5 bg-white/10 rounded-lg text-xs font-bold border border-white/10 animate-in zoom-in">
                  {sig}
                </span>
              ))
            )}
          </div>
        </div>

        {/* Live Transcription */}
        <div className="space-y-4">
          <h3 className="text-xs font-black uppercase text-white/40 tracking-widest flex items-center gap-2">
             <Mic className="w-4 h-4" /> Live Transcription
          </h3>
          <div className="space-y-3">
            {transcription.map((t, i) => (
              <div key={i} className={`p-4 rounded-2xl max-w-[85%] text-sm ${t.role === 'scammer' ? 'bg-red-500/20 text-red-100 border border-red-500/30 self-start' : 'bg-white/5 text-white/80 self-end ml-auto'}`}>
                {t.text}
              </div>
            ))}
            {processing && (
              <div className="flex gap-1 p-2">
                <div className="w-1.5 h-1.5 bg-white/40 rounded-full animate-bounce"></div>
                <div className="w-1.5 h-1.5 bg-white/40 rounded-full animate-bounce [animation-delay:0.2s]"></div>
                <div className="w-1.5 h-1.5 bg-white/40 rounded-full animate-bounce [animation-delay:0.4s]"></div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Controls */}
      <div className="p-8 bg-black/40 border-t border-white/10 space-y-6">
        {!isRecording ? (
          <button 
            onClick={startAnalysis}
            className="w-full py-5 bg-red-600 rounded-2xl font-black text-lg flex items-center justify-center gap-3 active:scale-95 transition-all shadow-xl shadow-red-900/40"
          >
            <Mic className="w-6 h-6" /> START LISTENING
          </button>
        ) : (
          <div className="grid grid-cols-2 gap-4">
            <button 
              onClick={() => setIsRecording(false)}
              className="py-4 bg-white/10 rounded-2xl font-bold flex items-center justify-center gap-2"
            >
              <MicOff className="w-5 h-5" /> Pause
            </button>
            <button 
              onClick={handleFinish}
              className="py-4 bg-green-600 rounded-2xl font-bold flex items-center justify-center gap-2"
            >
              <CheckCircle className="w-5 h-5" /> Generate Report
            </button>
          </div>
        )}
        <p className="text-[10px] text-center text-white/40 uppercase tracking-widest font-bold">
          End-to-End Encrypted Analysis • Thai Law Integrated
        </p>
      </div>

      {/* Processing Modal Overlay */}
      {processing && !isRecording && (
        <div className="absolute inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-[100] p-10 text-center">
          <div className="space-y-6">
            <div className="w-16 h-16 border-4 border-red-500 border-t-transparent rounded-full animate-spin mx-auto"></div>
            <div className="space-y-2">
              <h2 className="text-xl font-bold">Generating Legal Intel</h2>
              <p className="text-sm text-white/60">AI is mapping transcription to Thai Criminal Code sections...</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
